name: test job outputs
on: [push]
jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            myoutput: ${{ steps.my_id.outputs.myoutput }}
        steps:
            - name: test
              id: my_id
              run: |
               echo "myoutput=testonly" >> $GITHUB_OUTPUT
            - name: use output
              run: |
               echo "this is my outputs ${{ steps.my_id.outputs.myoutput }}"
    job2:
        runs-on: ubuntu-latest  
        needs: job1
        steps:
            - name: use output from job1
              run: |
               echo "this is my outputs from job1 ${{ needs.job1.outputs.myoutput }}"

